import Footer from "@/Components/Common/Footer";
import Header from "@/Components/Common/Header";

export const metadata = {
  title: "webmarkio agency ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <>
  <Header/>
  {children}
  <Footer />
  </>
  );
}
